### ISSUE TITLE
About Table Parsing in mPLUG-DocOwl1.5 work

### ISSUE THREAD

**Issue by SWHL** [X-PLUG/mPLUG-DocOwl#21]
Thanks for your great work. 

I have a small question:  In the Table Parsing section, the text  converts all table representations from HTML to Markdown format.

But the table syntax in Markdown does not support merging rows or columns. It says that tags like <ROWSPAN=x> or <COLSPAN=y> are added in the paper.

Why not just use LaTeX code to represent the table? MMD format is compatible with table LaTeX.

At same time, there is another question: in the inference phase, the model outputs the results of the transformed table, which can not be directly rendered. This is because the output format is neither LaTeX format nor Markdown format.

**Comment by HAWLYQ** [comment]
Hi @SWHL, we also took into account using Latex to represent tables. We finally chose markdown because it's the most concise way to convey the structure information of the table. The extended Markdown code can be easily transferred to HTML code, so rendering the image with the model outputs is not a problem. 
If you want to use text sequences to represent not only structure information but also style information, such as font size, and font color, we agree that HTML/latex codes are better choices.

**Comment by SWHL** [comment]
Thanks, it's very clear. 
By the way,  I am looking forward to the release of DocStruct4M and DocReason25k

**Comment by HAWLYQ** [comment]
Thanks for your attention, DocStruct4M and DocReason25k will be released in this week~

**Comment by HAWLYQ** [comment]
> Thanks, it's very clear. 
> 
> By the way,  I am looking forward to the release of DocStruct4M and DocReason25k

**Comment by HAWLYQ** [comment]
> Thanks, it's very clear. By the way, I am looking forward to the release of DocStruct4M and DocReason25k

Hi, @SWHL, both DocStruct4M and DocReason25k have been released, hope it helps~

**Comment by SWHL** [comment]
Thanks.
