### ISSUE TITLE
The images being sliced vertically. How can I make it horizontal.

### ISSUE THREAD

**Issue by rjmehta1993** [X-PLUG/mPLUG-DocOwl#56]
Hi, thanks for the amazing model. 

I added the intermediate images of the grid anchor. I see the images are sliced vertically. How can I make it horizontal? 

Original Image: 
<img width="946" alt="Screenshot 2024-04-19 at 11 26 24 AM" src="https://github.com/X-PLUG/mPLUG-DocOwl/assets/159200726/e8dfd9d2-d0dd-4e37-9881-3db27403103b">
----------------
Intermediate anchor sliced image ("grid_9")
![0_intermediate](https://github.com/X-PLUG/mPLUG-DocOwl/assets/159200726/40bad36f-26b1-4e9d-8e52-b1f014591f08)

**Comment by HAWLYQ** [comment]
Hi, @rjmehta1993 , sry, I don't quite understand "the images are sliced vertically". As shown in your sliced image, the raw image is cropped with the 3x3 shape and then horizontally concatenated.

**Comment by rjmehta1993** [comment]
Hey, thanks for the quick reply. If you see the slicing, the slice is breaking the context of columns. 
If I avoid slicing by keeping grid_1, the resolution is very low. The slicing breaks the column and index of the table, thus if I ask a simple question "What is the management fee for column ITD?" It fails to answer. 

Can I slice it horizontally? Something like in the bottom. 

![0_intermediate](https://github.com/X-PLUG/mPLUG-DocOwl/assets/159200726/de614d78-3a7e-4d25-b1e8-c20feeee5766)

**Comment by HAWLYQ** [comment]
Hi, @rjmehta1993 , sry, we currently don't support cropping a global image into multiple rectangular.

But, I think the failure of our model to answer the question is not due to the cropping but the Non-standard row-column relationships in this image.

Actually, I have tried parsing texts in the image with our[ HuggingFace demo](https://huggingface.co/spaces/mPLUG/DocOwl), our model could well organize texts as the structure in the image, as shown below. This validates that the 2x3 cropping doesn't influence the model to understand texts at the same row.
![image](https://github.com/X-PLUG/mPLUG-DocOwl/assets/12978686/b55ac63d-15c3-4cb6-8c83-32bff8f816cd)

**Comment by rjmehta1993** [comment]
I agree. The problem is not parsing or recognizing the text. But the problem is the spatial relation of column and index on the question. 

It is not able to map the column and index to the question if the column is far from the index. 

Not sure why. But thanks for this amazing model.

**Comment by HAWLYQ** [comment]
> I agree. The problem is not parsing or recognizing the text. But the problem is the spatial relation of column and index on the question. 
> 
> 
> 
> It is not able to map the column and index to the question if the column is far from the index. 
> 
> 
> 
> Not sure why. But thanks for this amazing model.

Thanks for your appreciation. Such non-standard col-row relationship is still a challenging problem. We will further enhance the general structure understanding abilities in our future work~
