### ISSUE TITLE
Question about OCR test results

### ISSUE THREAD

**Issue by sky-fly97** [X-PLUG/mPLUG-DocOwl#68]
Hi, I input a image to test **mplug-docowl1.5-chat**, prompt is ` Please print the full content of the 4.3 section.`, but I found that he always stops halfway through the output. The answer is `For real world use, we must detect and rectify StegaS-tamps within a wide field of view image before decoding them, since the decoder network alone is not designed to handle full detection within a much larger image. We fine-tune an off-the-shelf semantic segmentation network BiSeNet to segment areas of the image that are believed to contain StegaStamps. The network is trained using a dataset of randomly sampled binary messages.`

![7152504872291](https://github.com/X-PLUG/mPLUG-DocOwl/assets/55578436/5e5f5847-d131-4e22-834a-4c74ff139c57)

**Comment by HAWLYQ** [comment]
Hi, @sky-fly97 , docowl1.5 and docowl1.5-Chat are mainly finetuned with QA data and their text reading ability is not as strong as docowl1.5-stage1 and docowl-Omni. 

I tested this image and your prompt with our [modelscope demo](https://modelscope.cn/studios/iic/mPLUG-DocOwl/summary) supported by the docowl-Omni, the output is 
```
[doc]     loss.
4.3. Detector
For real world use, we must detect and rectify StegaS-
within a wide field of view image before decoding
them, since the decoder network alone is not designed to han-
detection within a much larger image. We fine-tune
off-the-shelf semantic segmentation network BiSeNet [?]
to segment areas of the image that are believed to contain
StegaStamps. The network is trained using a dataset of ran-
embedded into high reso-
lution images sampled from DIV2K [?]. At test time, we fit
a quadrilateral to the convex hull of each of the network’s
homography to warp each
quadrilateral back to a 400 x 400 pixel image for parsing by
the decoder.
4.4. Encoder/Decoder Training Procedure
During training, we use images from the
MIRFLICKR dataset [?] (resampled to 400 x 400 resolution)
combined with randomly sampled binary messages. [/doc]  
```
Our model can parse all texts but fails to judge which texts belong to section 4.3. This is mainly due to a lack of training samples to help the model understand the structure of papers. 

We have released the finetuning codes based on docowl1.5 models, you can try finetuning a stronger expert model according to your personal needs~ I think understanding the paper structure will not be a very difficult task~

**Comment by sky-fly97** [comment]
Thanks~
